In [1]:
import numpy as np  # NUMPY 
import random

In [2]:
a = np.array([[1,2,3],[5,6,7],[9,9,9]], dtype=np.int16)  # 
print(a)
print(a[0])
a.dtype

[[1 2 3]
 [5 6 7]
 [9 9 9]]
[1 2 3]


dtype('int16')

In [3]:
np.arange(10,100,5).reshape(3,6)

array([[10, 15, 20, 25, 30, 35],
       [40, 45, 50, 55, 60, 65],
       [70, 75, 80, 85, 90, 95]])

In [4]:
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [5]:
np.arange(10000).reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [11]:
a = np.array([[3,45,67], [123,56,78], [65, 12, 89]])
b = np.array([[43,5,57], [12,66,188], [543, 76,87]])
a + b

array([[ 46,  50, 124],
       [135, 122, 266],
       [608,  88, 176]])

In [3]:
rnd = np.random.default_rng(1)
a = rnd.random((4,4))
print(a)

[[0.51182162 0.9504637  0.14415961 0.94864945]
 [0.31183145 0.42332645 0.82770259 0.40919914]
 [0.54959369 0.02755911 0.75351311 0.53814331]
 [0.32973172 0.7884287  0.30319483 0.45349789]]


In [4]:
a *= 2
print(a)

[[1.02364325 1.90092739 0.28831923 1.89729889]
 [0.6236629  0.8466529  1.65540519 0.81839827]
 [1.09918738 0.05511823 1.50702622 1.07628663]
 [0.65946343 1.57685741 0.60638966 0.90699578]]


In [5]:
b = np.arange(16).reshape(4,4)
a += b
print(a)
a.max()

[[ 1.02364325  2.90092739  2.28831923  4.89729889]
 [ 4.6236629   5.8466529   7.65540519  7.81839827]
 [ 9.09918738  9.05511823 11.50702622 12.07628663]
 [12.65946343 14.57685741 14.60638966 15.90699578]]


15.906995778961303

In [10]:
c = np.linspace(0,1,6).reshape(2,3)
print(c)
c[0].sum(axis=0)

[[0.  0.2 0.4]
 [0.6 0.8 1. ]]


0.6000000000000001

In [11]:
d = np.ones(12)
print(d)
d.sum()

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


12.0

In [12]:
a = np.arange(20)*2
print(a)
print(a[3])
print(a[3:])
print(a[-1])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
6
[ 6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
38


In [13]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
a[0:4,0]

array([1., 1., 1.])

In [15]:
b = rnd.random((5,5))
print(b)
for row in b:
    print(row)

[[0.1340417  0.40311299 0.20345524 0.26231334 0.75036467]
 [0.28040876 0.48519097 0.9807372  0.96165719 0.72478994]
 [0.54122686 0.2768912  0.16065201 0.96992541 0.51606859]
 [0.11586561 0.62348976 0.77668311 0.6130033  0.9172977 ]
 [0.03959288 0.52858926 0.45933588 0.06234958 0.64132817]]
[0.1340417  0.40311299 0.20345524 0.26231334 0.75036467]
[0.28040876 0.48519097 0.9807372  0.96165719 0.72478994]
[0.54122686 0.2768912  0.16065201 0.96992541 0.51606859]
[0.11586561 0.62348976 0.77668311 0.6130033  0.9172977 ]
[0.03959288 0.52858926 0.45933588 0.06234958 0.64132817]


In [16]:
for row in b.flat:
    print(row)

0.13404169724716475
0.40311298644712923
0.20345524067614962
0.2623133404418495
0.7503646726300526
0.2804087579860399
0.48519097443163506
0.9807371998012386
0.9616571936637868
0.7247899407735336
0.5412268555474342
0.2768912040453708
0.16065200877512686
0.9699254132161326
0.5160685855478787
0.11586561247077032
0.6234897555375004
0.776683114342298
0.6130033010530405
0.9172977047909027
0.03959287666420286
0.5285892632600216
0.4593358828854037
0.0623495791498756
0.641328169139375


In [17]:
b.resize(2,10)
print(b)

[[0.1340417  0.40311299 0.20345524 0.26231334 0.75036467 0.28040876
  0.48519097 0.9807372  0.96165719 0.72478994]
 [0.54122686 0.2768912  0.16065201 0.96992541 0.51606859 0.11586561
  0.62348976 0.77668311 0.6130033  0.9172977 ]]


In [18]:
b.reshape(5,4)

array([[0.1340417 , 0.40311299, 0.20345524, 0.26231334],
       [0.75036467, 0.28040876, 0.48519097, 0.9807372 ],
       [0.96165719, 0.72478994, 0.54122686, 0.2768912 ],
       [0.16065201, 0.96992541, 0.51606859, 0.11586561],
       [0.62348976, 0.77668311, 0.6130033 , 0.9172977 ]])

In [52]:
np.split(b,2)

[array([[0.1340417 , 0.40311299, 0.20345524, 0.26231334, 0.75036467,
         0.28040876, 0.48519097, 0.9807372 , 0.96165719, 0.72478994]]),
 array([[0.54122686, 0.2768912 , 0.16065201, 0.96992541, 0.51606859,
         0.11586561, 0.62348976, 0.77668311, 0.6130033 , 0.9172977 ]])]

In [55]:
np.fromfunction(lambda x,j: x+j, (3,3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [58]:
b = rnd.random((5))
print(b)
sorted_b = np.sort(b)
print(sorted_b)
sorted_b[::-1]

[0.78709694 0.19161626 0.80236416 0.19132393 0.08155262]
[0.08155262 0.19132393 0.19161626 0.78709694 0.80236416]


array([0.80236416, 0.78709694, 0.19161626, 0.19132393, 0.08155262])